sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t haoly122/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haoly122/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react1422"
  env: "Dockerreact1422-env"
  bucket_name: "elasticbeanstalk-eu-west-1-427205730437"
  bucket_path: "docker-react1422"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
